# -*- coding: utf-8 -*-
"""plant-diseases-identification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qiozTPxm0ObCNgoIT0hgTEheOPBmkPhY
"""

!pip install PyDrive

import os
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

download = drive.CreateFile({'id': '1LehLXl5Wg_1Mtp78EmbkDxjoHf6s6nWx'})
download.GetContentFile('plant_disease_dataset.zip')

!unzip -u "/content/plant_disease_dataset.zip" -d "/content/dataset"

